[build]
  publish = "public"         # Change to your static output folder (e.g. ".", "dist", "build", etc.)
  command = "npm run build"  # Or "pnpm run build" if you use pnpm
  functions = "functions"    # Remove if you do not have serverless functions

[build.environment]
  NODE_VERSION = "22.21.1"
  NODE_ENV = "production"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
