[build]
  command = "pnpm run build"
  publish = ".next"
  functions = "functions"

[build.environment]
  NODE_VERSION = "22.21.1"
  NODE_ENV = "production"

[build.processing]
  skip_processing = false

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
